apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: choreov3
servers: 1
agents: 2
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
      - arg: "--disable-network-policy"
        nodeFilters:
          - server:*
      - arg: "--flannel-backend=none"
        nodeFilters:
          - server:*
