---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-tls-cert-gen-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-tls-cert-gen-clusterrole
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - create
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-tls-cert-gen-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: 
  - cert-manager.io
  resources:
  - certificates
  verbs: 
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-tls-cert-gen-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: gateway-tls-cert-gen-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gateway-tls-cert-gen-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-tls-cert-gen-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: gateway-tls-cert-gen-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gateway-tls-cert-gen-role
  apiGroup: rbac.authorization.k8s.io
