apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager-resources-{{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccountName: gateway-tls-cert-gen-sa
      containers:
      - name: create-resources
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - |
            echo "Waiting for cert-manager pods to be ready..."
            # adds the following wait to avoid race condition where the certs can be created before cert-manager is ready  
            kubectl wait --namespace {{ .Values.namespace | default .Release.Namespace }} \
            --for=condition=Ready pods \
            -l "app.kubernetes.io/name in (cert-manager, cainjector, webhook)" \
            --timeout=900s
            echo "Cert-manager pods are ready. proceeding with cert creation.."
            set -e
            echo "Creating ClusterIssuer"
            cat <<EOF | kubectl apply -f -
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: selfsigned-issuer
            spec:
              selfSigned: {}
            EOF

            echo "Creating Certificate"
            cat <<EOF | kubectl apply -f -
            apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: selfsigned-cert
              namespace: {{ .Values.namespace | default .Release.Namespace }}
            spec:
              secretName: envoy-gateway-tls-secret
              issuerRef:
                name: selfsigned-issuer
                kind: ClusterIssuer
              dnsNames:
                - choreo.local
                - '*.choreo.local'
            EOF
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      restartPolicy: OnFailure
  backoffLimit: 5
