apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
 name: allow-kube-dns-and-kubelet
spec:
 endpointSelector:
   matchLabels:
     user_app: 'true'
 egress:
   - toEndpoints:
       - matchLabels:
           k8s-app: kube-dns
           k8s:io.kubernetes.pod.namespace: kube-system
     toPorts:
       - ports:
           - port: '53'
             protocol: UDP
 ingress:
   - fromEntities:
       - host
       - remote-node
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-world
spec:
  endpointSelector:
    matchLabels:
      user_app: 'true'
  egress:
    - toCIDRSet:
        - cidr: 0.0.0.0/0
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-user-apps-to-internal-gateway
spec:
  endpointSelector:
    matchLabels:
      user_app: 'true'
  egress:
    - toEndpoints:
       - matchLabels:
          "gateway.envoyproxy.io/owning-gateway-name": gateway-internal
          "k8s:io.kubernetes.pod.namespace": choreo-dp
  ingress:
    - fromEndpoints:
       - matchLabels:
          "gateway.envoyproxy.io/owning-gateway-name": gateway-internal
          "k8s:io.kubernetes.pod.namespace": choreo-dp
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-user-apps-to-external-gateway
spec:
  endpointSelector:
    matchLabels:
      user_app: 'true'
  ingress:
    - fromEndpoints:
       - matchLabels:
          "gateway.envoyproxy.io/owning-gateway-name": gateway-external
          "k8s:io.kubernetes.pod.namespace": choreo-dp

