apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-external
spec:
  gatewayClassName: gateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: envoy-gateway-tls-secret
            namespace: {{ $.Values.namespace | default $.Release.Namespace }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-internal
spec:
  gatewayClassName: gateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: envoy-gateway-tls-secret
            namespace: {{ $.Values.namespace | default $.Release.Namespace }}
