# Default values for choreo-opensource-dp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metricsServer:
  enabled: false
  kubeletInsecureTlsEnabled: true

gateway-helm:
   config:
      envoyGateway:
         rateLimit:
            backend:
               type: Redis
               redis:
                  url: redis.choreo-system-dp.svc.cluster.local:6379

vault:
   server:
      resources:
         requests:
            memory: 64Mi
            cpu: 50m
         limits:
            memory: 128Mi
            cpu: 100m
      dev:
         enabled: true
         devRootToken: "root"
         logLevel: "info"
   injector:
      resources:
         requests:
            memory: 64Mi
            cpu: 50m
         limits:
            memory: 128Mi
            cpu: 100m
argo-workflows:
   controller:
      resources:
         limits:
            memory: 64Mi
            cpu: 50m
         requests:
            memory: 32Mi
            cpu: 25m
   server:
      resources:
         limits:
            memory: 64Mi
            cpu: 50m
         requests:
            memory: 32Mi
            cpu: 25m
   crds:
      keep: false
   workflow:
      serviceAccount:
         create: true
   workflowNamespaces:
      - argo-build

registry:
   # -- Resource limits and requests for the registry
   resources:
      limits:
         memory: 256Mi
         cpu: 100m
      requests:
         memory: 128Mi
         cpu: 50m

gateway-helm:
   deployment:
      envoyGateway:
         resources:
            limits:
               cpu: 200m
               memory: 256Mi
            requests:
               cpu: 100m
               memory: 128Mi

cert-manager:
   enabled: true
   crds:
      enabled: true
   # resources for cert manager controller
   resources:
      requests:
         cpu: 10m
         memory: 32Mi
      limits:
         cpu: 50m
         memory: 64Mi
   cainjector:
      resources:
         requests:
            cpu: 10m
            memory: 32Mi
         limits:
            cpu: 50m
            memory: 64Mi
   webhook:
      resources:
         requests:
            cpu: 10m
            memory: 32Mi
         limits:
            cpu: 50m
            memory: 64Mi
