---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.choreo.dev
  resources:
  - environments
  - organizations
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.choreo.dev
  resources:
  - environments/finalizers
  - organizations/finalizers
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - core.choreo.dev
  resources:
  - environments/status
  - organizations/status
  - projects/status
  verbs:
  - get
  - patch
  - update
