apiVersion: core.choreo.dev/v1
kind: Project
metadata:
  name: internal-apps
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Internal Applications
    core.choreo.dev/description: This project contains components that are used by companies internal applications
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/name: internal-apps
spec:
  deploymentPipelineRef: default-deployment-pipeline
