apiVersion: core.choreo.dev/v1
kind: Project
metadata:
  name: wso2-internal-apps
  annotations:
    core.choreo.dev/display-name: Internal Applications
    core.choreo.dev/description: This project contains components that are used by WSO2 internal applications
  labels:
    core.choreo.dev/organization: wso2
    core.choreo.dev/name: internal-apps
spec:
  deploymentPipelineRef: wso2-default-deployment-pipeline
