apiVersion: core.choreo.dev/v1
kind: Organization
metadata:
  annotations:
    core.choreo.dev/display-name: Default Organization
    core.choreo.dev/description: This is the default organization for this setup
  labels:
    core.choreo.dev/name: default-organization
  name: default-organization
spec:
