## Append samples of your project ##
resources:
- core_v1_organization.yaml
- core_v1_project.yaml
- core_v1_environment.yaml
- core_v1_dataplane.yaml
- core_v1_deploymentpipeline.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
