## Append samples of your project ##
resources:
  - core_v1_organization.yaml
  - core_v1_build.yaml
  - core_v1_project.yaml
- core_v1_deployableartifact.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
