## Sample Organization kind (Cluster-scoped)
apiVersion: core.choreo.dev/v1
kind: Organization
metadata:
  annotations:
    core.choreo.dev/display-name: Default Organization
    core.choreo.dev/description: This is the default organization for this setup
  labels:
    core.choreo.dev/name: default-organization
  name: default-organization
spec:

---

## Sample DataPlane kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: DataPlane
metadata:
  name: dp-local
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Local Data Plane
    core.choreo.dev/description: Data plane in KinD cluster
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/name: dp-local
spec:
  kubernetesCluster:
    name: kind-cluster-1
    connectionConfigRef: kind-cluster-1-connection-config
    featureFlags:
      cilium: true
      scaleToZero: true
      gatewayType: envoy
  gateway:
    publicVirtualHost: choreoapis.local
    organizationVirtualHost: internal.choreoapis.local
---
## Sample DeploymentPipeline kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: DeploymentPipeline
metadata:
  name: default-deployment-pipeline
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Default Deployment Pipeline
    core.choreo.dev/description: Allows promoting from dev to production
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/name: default-deployment-pipeline
spec:
  promotionPaths:
    - sourceEnvironmentRef: development
      targetEnvironmentRefs:
        - name: staging
          requiresApproval: false
        - name: production
          isManualApprovalRequired: true
    - sourceEnvironmentRef: staging
      targetEnvironmentRefs:
        - name: production
          requiresApproval: true
---
## Sample Environment kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: Environment
metadata:
  name: development
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Development Environment
    core.choreo.dev/description: The environment where you can play around
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/name: development
spec:
  dataPlaneRef: dp-local #TODO: Name or label selector?
  isProduction: false
  dnsPrefix: local-dev
---
## Sample Project kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: Project
metadata:
  name: internal-apps
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Internal Applications
    core.choreo.dev/description: This project contains components that are used by WSO2 internal applications
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/name: internal-apps
spec:
  deploymentPipelineRef: default-deployment-pipeline
---
## Sample Component kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: Component
metadata:
  name: time-logger
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Time Logger
    core.choreo.dev/description: This component will print the time
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/project: internal-apps
    core.choreo.dev/name: time-logger
spec:
  type: ScheduledTask
  source:
    gitRepository:
      url: https://github.com/wso2/choreo-samples
    authentication:
      secretRef: choreo-bot-git-pat
---
## Sample DeploymentTrack kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: DeploymentTrack
metadata:
  name: time-logger-dt
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Deployment Track
    core.choreo.dev/description: This deployment track will print time
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/project: internal-apps
    core.choreo.dev/component: time-logger
    core.choreo.dev/name: time-logger-dt
spec:
  buildTemplateSpec:
    branch: main
    path: docker-time-logger-schedule
    buildConfiguration:
      buildpack:
        name: Go
---
## Sample Build kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: Build
metadata:
  name: time-logger-01
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Build 1
    core.choreo.dev/description: Build 01
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/project: internal-apps
    core.choreo.dev/component: time-logger
    core.choreo.dev/deployment-track: time-logger-dt
    core.choreo.dev/name: time-logger-01
spec:
  branch: main
  path: docker-time-logger-schedule
  buildConfiguration:
    #    docker:
    #      context: docker-time-logger-schedule
    #      dockerfilePath: /docker-time-logger-schedule/Dockerfile
    buildpack:
      name: Go
#      version: "1.22"

---
#### Sample Deployment kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: Deployment
metadata:
  name: time-logger-01-deployment-development
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Deployment of Time Logger
    core.choreo.dev/description: This deployment will print the time
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/project: internal-apps
    core.choreo.dev/environment: development
    core.choreo.dev/component: time-logger
    core.choreo.dev/deployment-track: time-logger-dt
    core.choreo.dev/name: development
spec:
  deploymentArtifactRef: time-logger-01

---
### Sample DeployableArtifact kind (Namespaced)
#apiVersion: core.choreo.dev/v1
#kind: DeployableArtifact
#metadata:
#  name: github-issue-reporter-daily-deployable-artifact-2024-12-10-1
#  namespace: default-organization
#  annotations:
#    core.choreo.dev/display-name: Daily Deployable Artifact
#    core.choreo.dev/description: Generated artifact from Build 2024-12-10 1
#  labels:
#    core.choreo.dev/organization: default-organization
#    core.choreo.dev/project: internal-apps
#    core.choreo.dev/component: github-issue-reporter
#    core.choreo.dev/deployment-track: daily
#    core.choreo.dev/name: build-2024-12-10-1
#spec:
#  targetArtifact:
#    fromBuildRef:
#      name: github-issue-reporter-daily-build-2024-12-10-1
#  configuration:
#    application:
#      env:
#        - key: GITHUB_REPOSITORY
#          value: https://github.com/wso2/product-apim
#      task:
#        disabled: false
#        schedule:
#          cron: "*/1 * * * *"
#          timezone: Asia/Colombo
