# Default values for cilium-cni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cilium:
  encryption:
    enabled: true
    type: wireguard
  envoyConfig:
    enabled: false
  envoy:
    enabled: false
  nodePort:
    enabled: true
  priorityClassName: system-node-critical
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
  operator:
    replicas: 1
    rollOutPods: true
    unmanagedPodWatcher:
      restart: true
    priorityClassName: system-cluster-critical
  startupProbe:
    failureThreshold: 600
  policyEnforcementMode: default
  routingMode: tunnel
  kubeProxyReplacement: false
  rollOutCiliumPods: true
waitJob:
  image: bitnami/kubectl:latest
