apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "choreo-controllers.fullname" . }}-manager-role
  labels:
  {{- include "choreo-controllers.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.choreo.dev
  resources:
  - components
  - dataplanes
  - deploymentpipelines
  - deploymenttracks
  - environments
  - organizations
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.choreo.dev
  resources:
  - components/finalizers
  - dataplanes/finalizers
  - deploymentpipelines/finalizers
  - deploymenttracks/finalizers
  - environments/finalizers
  - organizations/finalizers
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - core.choreo.dev
  resources:
  - components/status
  - dataplanes/status
  - deploymentpipelines/status
  - deploymenttracks/status
  - environments/status
  - organizations/status
  - projects/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "choreo-controllers.fullname" . }}-manager-rolebinding
  labels:
  {{- include "choreo-controllers.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "choreo-controllers.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "choreo-controllers.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
