apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "choreo-controllers.fullname" . }}-manager-role
  labels:
  {{- include "choreo-controllers.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflowtaskresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.choreo.dev
  resources:
  - builds
  - components
  - dataplanes
  - deployableartifacts
  - deploymentpipelines
  - deployments
  - deploymenttracks
  - environments
  - organizations
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.choreo.dev
  resources:
  - builds/finalizers
  - components/finalizers
  - dataplanes/finalizers
  - deployableartifacts/finalizers
  - deploymentpipelines/finalizers
  - deployments/finalizers
  - deploymenttracks/finalizers
  - environments/finalizers
  - organizations/finalizers
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - core.choreo.dev
  resources:
  - builds/status
  - components/status
  - dataplanes/status
  - deployableartifacts/status
  - deploymentpipelines/status
  - deployments/status
  - deploymenttracks/status
  - environments/status
  - organizations/status
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "choreo-controllers.fullname" . }}-manager-rolebinding
  labels:
  {{- include "choreo-controllers.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "choreo-controllers.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "choreo-controllers.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
